/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
DROP TABLE "SYSTEM_DEPT";
DROP TABLE "SYSTEM_MENU";
DROP TABLE "SYSTEM_POST";
DROP TABLE "SYSTEM_ROLE";
DROP TABLE "SYSTEM_ROLE_MENU";
DROP TABLE "SYSTEM_USERS";
DROP TABLE "SYSTEM_USER_POST";
DROP TABLE "SYSTEM_USER_ROLE";
DROP TABLE "SYSTEM_DICT_DATA";
DROP TABLE "SYSTEM_DICT_TYPE";

DROP SEQUENCE "SYSTEM_DEPT_SEQ";
DROP SEQUENCE "SYSTEM_MENU_SEQ";
DROP SEQUENCE "SYSTEM_POST_SEQ";
DROP SEQUENCE "SYSTEM_ROLE_SEQ";
DROP SEQUENCE "SYSTEM_ROLE_MENU_SEQ";
DROP SEQUENCE "SYSTEM_USER_SEQ";
DROP SEQUENCE "SYSTEM_USER_POST_SEQ";
DROP SEQUENCE "SYSTEM_USER_ROLE_SEQ";
DROP SEQUENCE "SYSTEM_DICT_DATA_SEQ";
DROP SEQUENCE "SYSTEM_DICT_TYPE_SEQ";

--部门表
CREATE TABLE "SYSTEM_DEPT"
(
    "ID"             NUMBER(20, 0)          NOT NULL,
    "NAME"           NVARCHAR2(30),
    "PARENT_ID"      NUMBER(20, 0)          NOT NULL,
    "SORT"           NUMBER(11, 0)          NOT NULL,
    "LEADER_USER_ID" NUMBER(20, 0),
    "PHONE"          NVARCHAR2(11),
    "EMAIL"          NVARCHAR2(50),
    "STATUS"         NUMBER(4, 0)           NOT NULL,
    "CREATOR"        NVARCHAR2(64),
    "CREATE_TIME"    DATE                   NOT NULL,
    "UPDATER"        NVARCHAR2(64),
    "UPDATE_TIME"    DATE                   NOT NULL,
    "TENANT_ID"      NUMBER(20, 0)          NOT NULL,
    "DELETED"        NUMBER(1, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_DEPT"."ID" IS '部门id';
COMMENT ON COLUMN "SYSTEM_DEPT"."NAME" IS '部门名称';
COMMENT ON COLUMN "SYSTEM_DEPT"."PARENT_ID" IS '父部门id';
COMMENT ON COLUMN "SYSTEM_DEPT"."SORT" IS '显示顺序';
COMMENT ON COLUMN "SYSTEM_DEPT"."LEADER_USER_ID" IS '负责人';
COMMENT ON COLUMN "SYSTEM_DEPT"."PHONE" IS '联系电话';
COMMENT ON COLUMN "SYSTEM_DEPT"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "SYSTEM_DEPT"."STATUS" IS '部门状态（0正常 1停用）';
COMMENT ON COLUMN "SYSTEM_DEPT"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_DEPT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_DEPT"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_DEPT"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_DEPT"."TENANT_ID" IS '租户编号';
COMMENT ON COLUMN "SYSTEM_DEPT"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_DEPT" IS '部门表';

CREATE SEQUENCE "SYSTEM_DEPT_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--菜单权限表
CREATE TABLE "SYSTEM_MENU"
(
    "ID"          NUMBER(20, 0) NOT NULL,
    "NAME"        NVARCHAR2(50) NOT NULL,
    "PERMISSION"  NVARCHAR2(100),
    "TYPE"        NUMBER(6, 0)  NOT NULL,
    "SORT"        NUMBER(11, 0) NOT NULL,
    "PARENT_ID"   NUMBER(20, 0) NOT NULL,
    "PATH"        NVARCHAR2(200),
    "ICON"        NVARCHAR2(100),
    "COMPONENT"   NVARCHAR2(255),
    "STATUS"      NUMBER(6, 0)  NOT NULL,
    "VISIBLE"     NVARCHAR2(4)  NOT NULL,
    "KEEP_ALIVE"  NVARCHAR2(4)  NOT NULL,
    "CREATOR"     NVARCHAR2(64),
    "CREATE_TIME" DATE          NOT NULL,
    "UPDATER"     NVARCHAR2(64),
    "UPDATE_TIME" DATE          NOT NULL,
    "DELETED"     NUMBER(6, 0)  NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_MENU"."ID" IS '菜单ID';
COMMENT ON COLUMN "SYSTEM_MENU"."NAME" IS '菜单名称';
COMMENT ON COLUMN "SYSTEM_MENU"."PERMISSION" IS '权限标识';
COMMENT ON COLUMN "SYSTEM_MENU"."TYPE" IS '菜单类型';
COMMENT ON COLUMN "SYSTEM_MENU"."SORT" IS '显示顺序';
COMMENT ON COLUMN "SYSTEM_MENU"."PARENT_ID" IS '父菜单ID';
COMMENT ON COLUMN "SYSTEM_MENU"."PATH" IS '路由地址';
COMMENT ON COLUMN "SYSTEM_MENU"."ICON" IS '菜单图标';
COMMENT ON COLUMN "SYSTEM_MENU"."COMPONENT" IS '组件路径';
COMMENT ON COLUMN "SYSTEM_MENU"."STATUS" IS '菜单状态';
COMMENT ON COLUMN "SYSTEM_MENU"."VISIBLE" IS '是否可见';
COMMENT ON COLUMN "SYSTEM_MENU"."KEEP_ALIVE" IS '是否缓存';
COMMENT ON COLUMN "SYSTEM_MENU"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_MENU"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_MENU"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_MENU"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_MENU"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_MENU" IS '菜单权限表';

CREATE SEQUENCE "SYSTEM_MENU_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--岗位信息表
CREATE TABLE "SYSTEM_POST"
(
    "ID"          NUMBER(20, 0)          NOT NULL,
    "CODE"        NVARCHAR2(64),
    "NAME"        NVARCHAR2(50),
    "SORT"        NUMBER(11, 0)          NOT NULL,
    "STATUS"      NUMBER(4, 0)           NOT NULL,
    "REMARK"      NVARCHAR2(500),
    "CREATOR"     NVARCHAR2(64),
    "CREATE_TIME" DATE                   NOT NULL,
    "UPDATER"     NVARCHAR2(64),
    "UPDATE_TIME" DATE                   NOT NULL,
    "TENANT_ID"   NUMBER(20, 0)          NOT NULL,
    "DELETED"     NUMBER(1, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_POST"."ID" IS '岗位ID';
COMMENT ON COLUMN "SYSTEM_POST"."CODE" IS '岗位编码';
COMMENT ON COLUMN "SYSTEM_POST"."NAME" IS '岗位名称';
COMMENT ON COLUMN "SYSTEM_POST"."SORT" IS '显示顺序';
COMMENT ON COLUMN "SYSTEM_POST"."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "SYSTEM_POST"."REMARK" IS '备注';
COMMENT ON COLUMN "SYSTEM_POST"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_POST"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_POST"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_POST"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_POST"."TENANT_ID" IS '租户编号';
COMMENT ON COLUMN "SYSTEM_POST"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_POST" IS '岗位信息表';

CREATE SEQUENCE "SYSTEM_POST_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--角色信息表
CREATE TABLE "SYSTEM_ROLE"
(
    "ID"                  NUMBER(20, 0)          NOT NULL,
    "NAME"                NVARCHAR2(30),
    "CODE"                NVARCHAR2(100),
    "SORT"                NUMBER(11, 0)          NOT NULL,
    "DATA_SCOPE"          NUMBER(4, 0)           NOT NULL,
    "DATA_SCOPE_DEPT_IDS" NVARCHAR2(500),
    "STATUS"              NUMBER(4, 0)           NOT NULL,
    "TYPE"                NUMBER(4, 0)           NOT NULL,
    "REMARK"              NVARCHAR2(500),
    "CREATOR"             NVARCHAR2(64),
    "CREATE_TIME"         DATE                   NOT NULL,
    "UPDATER"             NVARCHAR2(64),
    "UPDATE_TIME"         DATE                   NOT NULL,
    "TENANT_ID"           NUMBER(20, 0)          NOT NULL,
    "DELETED"             NUMBER(1, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_ROLE"."ID" IS '角色ID';
COMMENT ON COLUMN "SYSTEM_ROLE"."NAME" IS '角色名称';
COMMENT ON COLUMN "SYSTEM_ROLE"."CODE" IS '角色权限字符串';
COMMENT ON COLUMN "SYSTEM_ROLE"."SORT" IS '显示顺序';
COMMENT ON COLUMN "SYSTEM_ROLE"."DATA_SCOPE" IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
COMMENT ON COLUMN "SYSTEM_ROLE"."DATA_SCOPE_DEPT_IDS" IS '数据范围(指定部门数组)';
COMMENT ON COLUMN "SYSTEM_ROLE"."STATUS" IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN "SYSTEM_ROLE"."TYPE" IS '角色类型';
COMMENT ON COLUMN "SYSTEM_ROLE"."REMARK" IS '备注';
COMMENT ON COLUMN "SYSTEM_ROLE"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_ROLE"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_ROLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_ROLE"."TENANT_ID" IS '租户编号';
COMMENT ON COLUMN "SYSTEM_ROLE"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_ROLE" IS '角色信息表';

CREATE SEQUENCE "SYSTEM_ROLE_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--角色和菜单关联表
CREATE TABLE "SYSTEM_ROLE_MENU"
(
    "ID"          NUMBER(20, 0)          NOT NULL,
    "ROLE_ID"     NUMBER(20, 0)          NOT NULL,
    "MENU_ID"     NUMBER(20, 0)          NOT NULL,
    "CREATOR"     NVARCHAR2(64),
    "CREATE_TIME" DATE                   NOT NULL,
    "UPDATER"     NVARCHAR2(64),
    "UPDATE_TIME" DATE                   NOT NULL,
    "TENANT_ID"   NUMBER(20, 0)          NOT NULL,
    "DELETED"     NUMBER(1, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."ID" IS '自增编号';
COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."TENANT_ID" IS '租户编号';
COMMENT ON COLUMN "SYSTEM_ROLE_MENU"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_ROLE_MENU" IS '角色和菜单关联表';

CREATE SEQUENCE "SYSTEM_ROLE_MENU_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--用户信息表
CREATE TABLE "SYSTEM_USERS"
(
    "ID"          NUMBER(20, 0)          NOT NULL,
    "USERNAME"    NVARCHAR2(30),
    "PASSWORD"    NVARCHAR2(100),
    "NICKNAME"    NVARCHAR2(30),
    "REMARK"      NVARCHAR2(500),
    "DEPT_ID"     NUMBER(20, 0),
    "POST_IDS"    NVARCHAR2(255),
    "EMAIL"       NVARCHAR2(50),
    "MOBILE"      NVARCHAR2(11),
    "SEX"         NUMBER(4, 0),
    "AVATAR"      NVARCHAR2(100),
    "STATUS"      NUMBER(4, 0)           NOT NULL,
    "LOGIN_IP"    NVARCHAR2(50),
    "LOGIN_DATE"  DATE,
    "CREATOR"     NVARCHAR2(64),
    "CREATE_TIME" DATE                   NOT NULL,
    "UPDATER"     NVARCHAR2(64),
    "UPDATE_TIME" DATE                   NOT NULL,
    "TENANT_ID"   NUMBER(20, 0)          NOT NULL,
    "DELETED"     NUMBER(1, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_USERS"."ID" IS '用户ID';
COMMENT ON COLUMN "SYSTEM_USERS"."USERNAME" IS '用户账号';
COMMENT ON COLUMN "SYSTEM_USERS"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SYSTEM_USERS"."NICKNAME" IS '用户昵称';
COMMENT ON COLUMN "SYSTEM_USERS"."REMARK" IS '备注';
COMMENT ON COLUMN "SYSTEM_USERS"."DEPT_ID" IS '部门ID';
COMMENT ON COLUMN "SYSTEM_USERS"."POST_IDS" IS '岗位编号数组';
COMMENT ON COLUMN "SYSTEM_USERS"."EMAIL" IS '用户邮箱';
COMMENT ON COLUMN "SYSTEM_USERS"."MOBILE" IS '手机号码';
COMMENT ON COLUMN "SYSTEM_USERS"."SEX" IS '用户性别';
COMMENT ON COLUMN "SYSTEM_USERS"."AVATAR" IS '头像地址';
COMMENT ON COLUMN "SYSTEM_USERS"."STATUS" IS '帐号状态（0正常 1停用）';
COMMENT ON COLUMN "SYSTEM_USERS"."LOGIN_IP" IS '最后登录IP';
COMMENT ON COLUMN "SYSTEM_USERS"."LOGIN_DATE" IS '最后登录时间';
COMMENT ON COLUMN "SYSTEM_USERS"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_USERS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_USERS"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_USERS"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_USERS"."TENANT_ID" IS '租户编号';
COMMENT ON COLUMN "SYSTEM_USERS"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_USERS" IS '用户信息表';

CREATE SEQUENCE "SYSTEM_USER_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--用户岗位表
CREATE TABLE "SYSTEM_USER_POST"
(
    "ID"          NUMBER(20, 0)           NOT NULL,
    "USER_ID"     NUMBER(20, 0)           NOT NULL,
    "POST_ID"     NUMBER(20, 0)           NOT NULL,
    "CREATOR"     NVARCHAR2(64),
    "CREATE_TIME" DATE                    NOT NULL,
    "UPDATER"     NVARCHAR2(64),
    "UPDATE_TIME" DATE                    NOT NULL,
    "DELETED"     NUMBER(1, 0)  DEFAULT 0 NOT NULL,
    "TENANT_ID"   NUMBER(20, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_USER_POST"."ID" IS 'id';
COMMENT ON COLUMN "SYSTEM_USER_POST"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "SYSTEM_USER_POST"."POST_ID" IS '岗位ID';
COMMENT ON COLUMN "SYSTEM_USER_POST"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_USER_POST"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_USER_POST"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_USER_POST"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_USER_POST"."DELETED" IS '是否删除';
COMMENT ON COLUMN "SYSTEM_USER_POST"."TENANT_ID" IS '租户编号';
COMMENT ON TABLE "SYSTEM_USER_POST" IS '用户岗位表';

CREATE SEQUENCE "SYSTEM_USER_POST_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--用户和角色关联表
CREATE TABLE "SYSTEM_USER_ROLE"
(
    "ID"          NUMBER(20, 0)          NOT NULL,
    "USER_ID"     NUMBER(20, 0)          NOT NULL,
    "ROLE_ID"     NUMBER(20, 0)          NOT NULL,
    "CREATOR"     NVARCHAR2(64),
    "CREATE_TIME" DATE,
    "UPDATER"     NVARCHAR2(64),
    "UPDATE_TIME" DATE,
    "TENANT_ID"   NUMBER(20, 0)          NOT NULL,
    "DELETED"     NUMBER(1, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."ID" IS '自增编号';
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."TENANT_ID" IS '租户编号';
COMMENT ON COLUMN "SYSTEM_USER_ROLE"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_USER_ROLE" IS '用户和角色关联表';

CREATE SEQUENCE "SYSTEM_USER_ROLE_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--字典数据表
CREATE TABLE "SYSTEM_DICT_DATA"
(
    "ID"          NUMBER(20, 0)          NOT NULL,
    "SORT"        NUMBER(11, 0)          NOT NULL,
    "LABEL"       NVARCHAR2(100),
    "VALUE"       NVARCHAR2(100),
    "DICT_TYPE"   NVARCHAR2(100),
    "STATUS"      NUMBER(4, 0)           NOT NULL,
    "COLOR_TYPE"  NVARCHAR2(100),
    "CSS_CLASS"   NVARCHAR2(100),
    "REMARK"      NVARCHAR2(500),
    "CREATOR"     NVARCHAR2(64),
    "CREATE_TIME" DATE                   NOT NULL,
    "UPDATER"     NVARCHAR2(64),
    "UPDATE_TIME" DATE                   NOT NULL,
    "DELETED"     NUMBER(1, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_DICT_DATA"."ID" IS '字典编码';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."SORT" IS '字典排序';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."LABEL" IS '字典标签';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."VALUE" IS '字典键值';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."COLOR_TYPE" IS '颜色类型';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."CSS_CLASS" IS 'css 样式';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."REMARK" IS '备注';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_DICT_DATA"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_DICT_DATA" IS '字典数据表';

CREATE SEQUENCE "SYSTEM_DICT_DATA_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

--字典类型表
CREATE TABLE "SYSTEM_DICT_TYPE"
(
    "ID"           NUMBER(20, 0)          NOT NULL,
    "NAME"         NVARCHAR2(100),
    "TYPE"         NVARCHAR2(100),
    "STATUS"       NUMBER(4, 0)           NOT NULL,
    "REMARK"       NVARCHAR2(500),
    "CREATOR"      NVARCHAR2(64),
    "CREATE_TIME"  DATE                   NOT NULL,
    "UPDATER"      NVARCHAR2(64),
    "UPDATE_TIME"  DATE                   NOT NULL,
    "DELETED_TIME" DATE,
    "DELETED"      NUMBER(1, 0) DEFAULT 0 NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
)
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."ID" IS '字典主键';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."NAME" IS '字典名称';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."TYPE" IS '字典类型';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."REMARK" IS '备注';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."CREATOR" IS '创建者';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."UPDATER" IS '更新者';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."DELETED_TIME" IS '删除时间';
COMMENT ON COLUMN "SYSTEM_DICT_TYPE"."DELETED" IS '是否删除';
COMMENT ON TABLE "SYSTEM_DICT_TYPE" IS '字典类型表';

CREATE SEQUENCE "SYSTEM_DICT_TYPE_SEQ" MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;